I'm sorry, but an uncaught exception occurred.

While running game code:
<<<<<<< HEAD
  File "game/script.rpy", line 98, in script call
    image bg marioland = "marioland.jpg"
  File "renpy/common/00console.rpy", line 765, in script call
    python in _console:
Exception: Sayer 'input' is not defined.
=======
  File "game/script.rpy", line 14, in script call
    "Nothing too scary, mind you. But it will help with making this game as fun for you as possible!"
  File "renpy/common/00console.rpy", line 765, in script call
    python in _console:
  File "game/script.rpy", line 392, in script
    $ late = true
  File "game/script.rpy", line 392, in <module>
    $ late = true
NameError: name 'true' is not defined
>>>>>>> 28fd57dcde5904560b17b821bb25dc88dd5d4745

-- Full Traceback ------------------------------------------------------------

Full traceback:
<<<<<<< HEAD
  File "game/script.rpy", line 98, in script call
    image bg marioland = "marioland.jpg"
  File "renpy/common/00console.rpy", line 765, in script call
    python in _console:
  File "<string>", line 1, in script
  File "/Users/James/Desktop/renpy-6.99.14.3-sdk/renpy/ast.py", line 624, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/James/Desktop/renpy-6.99.14.3-sdk/renpy/ast.py", line 537, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'input' is not defined.
=======
  File "game/script.rpy", line 14, in script call
    "Nothing too scary, mind you. But it will help with making this game as fun for you as possible!"
  File "renpy/common/00console.rpy", line 765, in script call
    python in _console:
  File "game/script.rpy", line 392, in script
    $ late = true
  File "G:\Downloadings\renpy-6.99.14.3-sdk\renpy\ast.py", line 862, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "G:\Downloadings\renpy-6.99.14.3-sdk\renpy\python.py", line 1888, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 392, in <module>
    $ late = true
NameError: name 'true' is not defined
>>>>>>> 28fd57dcde5904560b17b821bb25dc88dd5d4745

Windows-8-6.2.9200
Ren'Py 6.99.14.3.3347
RenPy 1.0
<<<<<<< HEAD
Thu May 31 14:05:09 2018
=======
Wed May 30 08:07:53 2018
>>>>>>> 28fd57dcde5904560b17b821bb25dc88dd5d4745
